version: "3.9"

services:
  frontend:
    image: ubuntu:24.04
    container_name: vue-frontend
    restart: always
    ports:
      - "8200:8080"

  backend:
    image: ubuntu:24.04
    container_name: fastapi-backend
    restart: always
    ports:
      - "8000:8000"

  elasticsearch:
    container_name: es-container
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.0  # ready made ES docker image
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
    ports:
      - "9200:9200"
