version: '3.9'
services:
  devcontainer:
    image: nodejs:21-alpine3.18
    volumes:
      - ../..:/workspaces:cached
#    network_mode: service:db
    command: sleep infinity
    ports:
      - "8080:8080"

#  db:
#    image: postgres:latest
#    restart: unless-stopped
#    volumes:
#      - postgres-data:/var/lib/postgresql/data
#    environment:
#      POSTGRES_PASSWORD: postgres
#      POSTGRES_USER: postgres
#      POSTGRES_DB: postgres
#    ports:
#      - "5432"

volumes:
  postgres-data:
